import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: ["700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["200", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${inter.variable} antialiased`}
      >
        <div className="flex flex-col items-center w-full min-h-screen">
          <header className="w-full flex justify-center items-start pointer-events-none z-50 mt-32">
            <div className={"text-white text-5xl font-thin pointer-events-auto select-none " + inter.variable} style={{fontFamily: 'var(--font-inter)', fontWeight: 175}}>What can I do for you?</div>
          </header>
          <div className="w-full flex justify-center mt-8">
            <div className="grid grid-cols-3 grid-rows-3 gap-4">
              {Array.from({ length: 9 }).map((_, i) => (
                <button
                  key={i}
                  className="bg-neutral-800 hover:bg-neutral-700 text-white rounded-xl w-80 h-56 shadow-md transition-colors text-5xl font-medium focus:outline-none focus:ring-2 focus:ring-blue-500"
                  aria-label={`Button ${i + 1}`}
                  title={`Button ${i + 1}`}
                >
                </button>
              ))}
            </div>
          </div>
          <div className="w-full flex justify-center mt-12">
            <div className="flex items-center w-[62rem] max-w-full">
              <button
                className="flex items-center justify-center w-14 h-14 rounded-full bg-neutral-800 hover:bg-neutral-700 text-white shadow-md transition-colors mr-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
                aria-label="Add"
                title="Add"
              >
                <span className="text-3xl font-light">+</span>
              </button>
              <input
                type="text"
                placeholder="Type your request..."
                className="flex-1 px-6 py-4 rounded-2xl bg-neutral-900 text-white text-xl shadow-md focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder:text-neutral-400"
              />
              <button
                className="flex items-center justify-center w-14 h-14 rounded-full bg-blue-600 hover:bg-blue-700 text-white shadow-md transition-colors ml-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
                aria-label="Send"
                title="Send"
              >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-7 h-7">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 19V5m0 0l-7 7m7-7l7 7" />
                </svg>
              </button>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
